"""
validate_failure_spectrum.py

Validates each step of the failure spectrum implementation against the
decoder-bench HDF5 trace generated by:

    circuit = stim.Circuit.generated('surface_code:rotated_memory_z',
                                     distance=7, rounds=7)
    circuit = NoiseModel.SI1000(0.001).noisy_circuit(circuit)
    generator = DatasetGen(circuit, matchable=True, name='my_dataset')
    generator.gen_syndromes(max_iterations=100, num_records=10000)

Known schema:
    check_matrix : (336, 5471) uint8   — H
    obs_matrix   : (1,   5471) uint8   — A
    priors       : (5471,)     float64
    syndromes    : (10000, 336) bool   — existing Monte Carlo shots
    observables  : (10000, 1)  bool   — logical outcomes for those shots

Usage:
    python validate_failure_spectrum.py --h5 path/to/my_dataset.h5
"""

import argparse
import sys
import time
import numpy as np
import h5py

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------

parser = argparse.ArgumentParser(description="Validate failure_spectrum.py steps")
parser.add_argument("--h5", required=True, help="Path to the decoder-bench HDF5 trace")
parser.add_argument("--decoder", default="auto",
                    help="Decoder to use: 'sparseblossom', 'belieffind', or 'auto'")
parser.add_argument("--trials", type=int, default=3000,
                    help="Trials per weight in the spectrum sweep (default 3000)")
parser.add_argument("--seed", type=int, default=42)
args = parser.parse_args()

PASS = "\033[92m  PASSED\033[0m"
FAIL = "\033[91m  FAILED\033[0m"
WARN = "\033[93m  WARNING\033[0m"

failures = []

def check(condition, label, detail=""):
    if condition:
        print(f"{PASS}  {label}")
    else:
        print(f"{FAIL}  {label}")
        if detail:
            print(f"         {detail}")
        failures.append(label)

def warn(condition, label, detail=""):
    if not condition:
        print(f"{WARN}  {label}")
        if detail:
            print(f"         {detail}")

# ---------------------------------------------------------------------------
# Step 0 — inspect the file
# ---------------------------------------------------------------------------

print("=" * 60)
print("STEP 0 — File inspection")
print("=" * 60)

try:
    with h5py.File(args.h5, 'r') as f:
        keys = list(f.keys())
        shapes = {k: f[k].shape for k in keys}
        dtypes = {k: f[k].dtype for k in keys}
except Exception as e:
    print(f"Could not open HDF5 file: {e}")
    sys.exit(1)

print(f"\n  File: {args.h5}")
for k in keys:
    print(f"    {k:<20} shape={shapes[k]}  dtype={dtypes[k]}")

REQUIRED = {'check_matrix', 'obs_matrix', 'priors', 'syndromes', 'observables'}
missing = REQUIRED - set(keys)
check(len(missing) == 0, "All required keys present",
      f"Missing: {missing}")

# ---------------------------------------------------------------------------
# Step 1 — load H, A, priors
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 1 — Load H, A, priors")
print("=" * 60)

with h5py.File(args.h5, 'r') as f:
    H          = f['check_matrix'][:].astype(np.uint8)
    A          = f['obs_matrix'][:].astype(np.uint8)
    priors     = f['priors'][:].astype(np.float64)
    syndromes  = f['syndromes'][:].astype(np.uint8)   # (10000, 336)
    observables= f['observables'][:].astype(np.uint8) # (10000, 1)

M, N = H.shape
K    = A.shape[0]
n_mc = syndromes.shape[0]

print(f"\n  H      : ({M}, {N})  — {M} detectors, {N} fault mechanisms")
print(f"  A      : ({K}, {N})  — {K} logical observable(s)")
print(f"  priors : shape={priors.shape}, "
      f"min={priors.min():.5f}, max={priors.max():.5f}")
print(f"  Monte Carlo shots: {n_mc}")

check(K == 1,
      "K=1 (single logical qubit)",
      f"Got K={K}")
check(H.shape[1] == N and A.shape[1] == N and priors.shape[0] == N,
      "H, A, priors all share the same N",
      f"H.N={H.shape[1]}, A.N={A.shape[1]}, priors.N={priors.shape[0]}")
check(set(np.unique(H)).issubset({0, 1}),
      "H is binary")
check(set(np.unique(A)).issubset({0, 1}),
      "A is binary")
check(np.all(priors > 0) and np.all(priors < 1),
      "All priors in (0, 1)")

# SI1000 at p=0.001 has exactly 4 distinct prior values
unique_priors = np.unique(np.round(priors, 8))
print(f"\n  Unique prior values: {unique_priors}")
check(len(unique_priors) <= 6,
      f"Small number of distinct priors ({len(unique_priors)}) — consistent with SI1000 model")

a = 1.0 - 1.0 / (2 ** K)
print(f"\n  Asymptote a = 1 - 1/2^K = {a}")
check(a == 0.5, "a=0.5 for K=1")

# ---------------------------------------------------------------------------
# Step 2 — build the decoder
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 2 — Build decoder")
print("=" * 60)

decoder = None
decoder_name = args.decoder

def try_sparseblossom():
    from decoder_bench.decoders import SparseBlossom
    return SparseBlossom(H, priors, A)

def try_belieffind():
    from decoder_bench.decoders import BeliefFind
    return BeliefFind(H, priors, A)

decoder_attempts = (
    [try_sparseblossom] if decoder_name == 'sparseblossom'
    else [try_belieffind] if decoder_name == 'belieffind'
    else [try_sparseblossom, try_belieffind]
)

for attempt in decoder_attempts:
    try:
        decoder = attempt()
        decoder_name = attempt.__name__.replace('try_', '')
        print(f"\n  Loaded decoder: {decoder_name}")
        break
    except Exception as e:
        print(f"  Could not load {attempt.__name__}: {e}")

check(decoder is not None, "Decoder loaded successfully")
if decoder is None:
    print("Cannot continue without a decoder.")
    sys.exit(1)

# Smoke test: zero syndrome → zero correction
t0 = time.perf_counter()
zero_syn    = np.zeros(M, dtype=np.uint8)
correction  = decoder.decode(zero_syn)
elapsed_ms  = (time.perf_counter() - t0) * 1000

check(correction.shape == (N,),
      f"Correction shape is ({N},)",
      f"Got {correction.shape}")
check(set(np.unique(correction)).issubset({0, 1}),
      "Correction is binary")
check(np.all((H @ correction) % 2 == zero_syn),
      "H @ correction = syndrome (syndrome equation satisfied)")
check(correction.sum() == 0,
      f"Zero syndrome → zero correction (weight={correction.sum()})")

print(f"\n  Single decode call: {elapsed_ms:.2f} ms")

# ---------------------------------------------------------------------------
# Step 3 — failure oracle
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 3 — Failure oracle (is_failure)")
print("=" * 60)

def is_failure(e, H, A, decoder):
    syndrome   = (H @ e) % 2
    correction = decoder.decode(syndrome.astype(np.uint8))
    return bool(np.any((A @ correction) % 2 != (A @ e) % 2))

# --- 3a: zero vector must not fail ---
e_zero = np.zeros(N, dtype=np.uint8)
check(not is_failure(e_zero, H, A, decoder),
      "f(0) = 0  (zero fault vector never fails)")

# --- 3b: all weight-1 faults ---
print(f"\n  Testing all {N} weight-1 faults...")
t0 = time.perf_counter()
w1_failures = []
for i in range(N):
    e = np.zeros(N, dtype=np.uint8)
    e[i] = 1
    if is_failure(e, H, A, decoder):
        w1_failures.append(i)
elapsed = time.perf_counter() - t0

print(f"  Weight-1 failures: {len(w1_failures)} / {N}  ({elapsed:.1f}s)")
check(len(w1_failures) == 0,
      "No weight-1 faults cause failure (d=7 onset > 1)")
if w1_failures:
    print(f"  Failing fault indices: {w1_failures[:10]}{'...' if len(w1_failures)>10 else ''}")

# --- 3c: cross-check against the stored Monte Carlo traces ---
# For each stored shot, compute syndrome from scratch via H @ e is not
# possible (we don't have the raw fault vectors). But we CAN check the
# inverse direction: pass the stored syndrome to the decoder and compare
# its predicted observable to the stored observable.
#
# A Monte Carlo "failure" in the trace means:
#   decoder.decode(syndrome) produced the wrong logical correction.
# We reproduce exactly this check here.

print(f"\n  Cross-checking oracle against {n_mc} stored Monte Carlo syndromes...")

t0 = time.perf_counter()
mc_predicted_fails = 0
mc_stored_fails    = 0

# stored observables: 1 means a logical error occurred
mc_stored_fails = int(observables.sum())

for i in range(n_mc):
    syn = syndromes[i].astype(np.uint8)
    c   = decoder.decode(syn)
    # predicted logical outcome: A @ correction (mod 2)
    predicted_obs = (A @ c) % 2          # shape (K,)
    stored_obs    = observables[i]        # shape (K,)
    if np.any(predicted_obs != stored_obs):
        mc_predicted_fails += 1

elapsed = time.perf_counter() - t0

mc_ler_stored    = mc_stored_fails    / n_mc
mc_ler_predicted = mc_predicted_fails / n_mc

print(f"  Stored   LER : {mc_ler_stored:.5f}  ({mc_stored_fails} / {n_mc})")
print(f"  Predicted LER: {mc_ler_predicted:.5f}  ({mc_predicted_fails} / {n_mc})")
print(f"  ({elapsed:.1f}s for {n_mc} decode calls)")

check(abs(mc_ler_stored - mc_ler_predicted) / max(mc_ler_stored, 1e-9) < 0.15,
      "Predicted LER matches stored LER within 15%",
      f"stored={mc_ler_stored:.5f} predicted={mc_ler_predicted:.5f}  "
      f"— mismatch may mean the wrong decoder class was loaded")

# Store the Monte Carlo LER as the ground truth reference for later steps
mc_ler = mc_ler_stored
print(f"\n  Monte Carlo LER reference: {mc_ler:.5f}")
print(f"  (Used in Step 8 to sanity-check P(q) at q=0.001)")

# ---------------------------------------------------------------------------
# Step 4 — fixed-weight sampler
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 4 — Fixed-weight sampler")
print("=" * 60)

def sample_fixed_weight(w, num_trials, H, A, decoder, rng):
    n = H.shape[1]
    failures = 0
    for _ in range(num_trials):
        e = np.zeros(n, dtype=np.uint8)
        e[rng.choice(n, size=w, replace=False)] = 1
        if is_failure(e, H, A, decoder):
            failures += 1
    return failures, num_trials

rng = np.random.default_rng(args.seed)

# Boundary: high weight should give f ≈ 0.5
print(f"\n  High-weight boundary (w=N//2={N//2}, 300 trials)...")
t0 = time.perf_counter()
fails_hi, trials_hi = sample_fixed_weight(N // 2, 300, H, A, decoder, rng)
f_hi = fails_hi / trials_hi
elapsed = time.perf_counter() - t0
print(f"  f(N//2) = {f_hi:.3f}  (expect ≈ a={a})  [{elapsed:.1f}s]")
check(0.35 < f_hi < 0.65,
      f"f(N//2) ≈ 0.5  [got {f_hi:.3f}]",
      "High-weight failure rate should be near the asymptote a=0.5")

# Onset scan: find w0 by incrementing from w=2 until failures appear
print(f"\n  Onset scan — searching for w0 (500 trials per weight)...")
w0_found = None
for w_scan in range(2, 12):
    f_scan, t_scan = sample_fixed_weight(w_scan, 500, H, A, decoder, rng)
    rate = f_scan / t_scan
    marker = " ← first failures" if f_scan > 0 and w0_found is None else ""
    print(f"    w={w_scan}: {f_scan}/{t_scan} failures  (f={rate:.4e}){marker}")
    if f_scan > 0 and w0_found is None:
        w0_found = w_scan

check(w0_found is not None,
      f"Onset weight w0 found: w0={w0_found}",
      "No failures found up to w=11 — check that the decoder is working")

# For d=7 circuit-level noise with a good decoder, expect w0 in [3, 5]
if w0_found is not None:
    check(2 <= w0_found <= 6,
          f"w0={w0_found} is plausible for d=7 circuit noise (expect 3–5)")
    print(f"\n  Using w0={w0_found} for Steps 5–8")

# ---------------------------------------------------------------------------
# Step 5 — failure spectrum over a weight range
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 5 — Failure spectrum estimation")
print("=" * 60)

def estimate_failure_spectrum(H, A, decoder, w_range, trials_per_weight, seed=0):
    rng  = np.random.default_rng(seed)
    spec = {}
    for w in w_range:
        fails, trials = sample_fixed_weight(w, trials_per_weight, H, A, decoder, rng)
        f_hat  = fails / trials
        stderr = np.sqrt(f_hat * (1 - f_hat) / trials) if trials > 0 else 0.0
        spec[w] = (f_hat, stderr)
    return spec

w0 = w0_found if w0_found is not None else 4
# Log-spaced weights from w0 up to ~N//10; cap at a reasonable upper limit
w_max  = min(N // 10, 80)
w_range = sorted(set(
    [w0] +
    list(range(w0, min(w0 + 6, w_max))) +
    [int(x) for x in np.geomspace(w0 + 2, w_max, 8).astype(int)]
))

print(f"\n  Weight range : {w_range}")
print(f"  Trials/weight: {args.trials}")
print(f"  (This is a validation run — use ≥50,000 trials/weight for production)\n")

t0 = time.perf_counter()
spectrum = estimate_failure_spectrum(
    H, A, decoder, w_range, args.trials, seed=args.seed
)
elapsed = time.perf_counter() - t0

print(f"\n  {'w':>5}  {'f(w)':>12}  {'±stderr':>10}  {'failures':>10}  bar")
print(f"  {'-'*5}  {'-'*12}  {'-'*10}  {'-'*10}  ---")
for w in sorted(spectrum):
    f_hat, stderr = spectrum[w]
    fails_approx  = int(round(f_hat * args.trials))
    bar_len = int(np.clip(f_hat * 50, 0, 50))
    bar = '█' * bar_len
    print(f"  {w:>5}  {f_hat:>12.4e}  {stderr:>10.2e}  {fails_approx:>10}  {bar}")
print(f"\n  Total time: {elapsed:.1f}s")

# Monotonicity check (allow small violations from sampling noise)
f_vals = [spectrum[w][0] for w in sorted(spectrum)]
stderrs = [spectrum[w][1] for w in sorted(spectrum)]
monotone_violations = 0
for i in range(1, len(f_vals)):
    # Allow up to 2-sigma downward violation
    if f_vals[i] < f_vals[i-1] - 2 * stderrs[i-1]:
        monotone_violations += 1

check(monotone_violations == 0,
      "Spectrum is monotonically non-decreasing (within 2σ)")

# Dynamic range: spectrum should span several orders of magnitude
f_nonzero = [f for f in f_vals if f > 0]
if len(f_nonzero) >= 2:
    dynamic_range = max(f_nonzero) / min(f_nonzero)
    check(dynamic_range > 10,
          f"Spectrum spans >10x dynamic range (got {dynamic_range:.1f}x)",
          "If range is small, extend w_range or increase trials at low weights")

# High-weight convergence toward a
f_high = spectrum[max(w_range)][0]
warn(abs(f_high - a) < 0.15,
     f"Highest-weight f={f_high:.3f} approaching asymptote a={a}",
     "Extend w_range to larger weights to see saturation")

# ---------------------------------------------------------------------------
# Step 6 — ansatz functions
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 6 — Ansatz functions")
print("=" * 60)

def f_ansatz_2(w, w0, f0, a):
    x = (1/a) * f0 * (w / w0) ** w0
    return a * (1 - np.exp(-x))

def f_ansatz_3(w, w0, f0, a, gamma):
    x = (1/a) * f0 * (w / w0) ** gamma
    return a * (1 - np.exp(-x))

def f_ansatz_5(w, w0, f0, a, gamma1, gamma2, wc):
    c          = 2
    transition = (1 + (w / wc) ** c) / (1 + (w0 / wc) ** c)
    power      = (w / w0) ** gamma1 * transition ** ((gamma2 - gamma1) / c)
    return a * (1 - np.exp(-(1/a) * f0 * power))

# Use plausible test parameters
test_w0, test_f0 = w0, 1e-4
test_params = dict(gamma1=w0 * 0.8, gamma2=w0 * 1.2, wc=float(w0 * 3))

print(f"\n  Test params: w0={test_w0}, f0={test_f0}, a={a}")
print(f"               gamma1={test_params['gamma1']:.2f}, "
      f"gamma2={test_params['gamma2']:.2f}, wc={test_params['wc']:.1f}")

# At w=w0: f_ansatz ≈ f0 (since 1-exp(-f0) ≈ f0 for small f0)
for name, fn, extra in [
    ('f^(2)', f_ansatz_2, {}),
    ('f^(3)', f_ansatz_3, {'gamma': w0 * 0.9}),
    ('f^(5)', f_ansatz_5, test_params),
]:
    val = fn(test_w0, test_w0, test_f0, a, **extra)
    rel_err = abs(val - test_f0) / test_f0
    check(rel_err < 0.05,
          f"{name}(w=w0) ≈ f0  [got {val:.4e}, expected {test_f0:.4e}, "
          f"rel_err={rel_err:.3f}]")

# Monotonicity
w_test = np.arange(w0, 100, dtype=float)
vals5  = np.array([f_ansatz_5(w, test_w0, test_f0, a, **test_params) for w in w_test])
check(np.all(np.diff(vals5) >= -1e-12),
      "f^(5) is monotonically non-decreasing")

# Asymptote
val_large = f_ansatz_5(10000, test_w0, test_f0, a, **test_params)
check(abs(val_large - a) < 0.001,
      f"f^(5)(w→∞) → a={a}  [got {val_large:.5f}]")

print(f"\n  f^(5) at selected weights:")
for w_show in [w0, w0*2, w0*4, w0*8, 100, 500]:
    v = f_ansatz_5(float(w_show), test_w0, test_f0, a, **test_params)
    print(f"    w={w_show:>5}  f^(5)={v:.5f}")

# ---------------------------------------------------------------------------
# Step 7 — fitting
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 7 — Ansatz fitting")
print("=" * 60)

from scipy.optimize import curve_fit

def fit_ansatz(spectrum, K, w0):
    a = 1.0 - 1.0 / (2 ** K)

    # Only fit points where we observed at least 1 failure
    ws      = np.array([w for w, (f, _) in sorted(spectrum.items()) if f > 0],
                       dtype=float)
    f_vals  = np.array([spectrum[int(w)][0] for w in ws])
    f_errs  = np.array([max(spectrum[int(w)][1], 1e-15) for w in ws])

    if len(ws) < 4:
        print(f"  Only {len(ws)} non-zero spectrum points — fit may be unreliable.")
        print("  Increase trials_per_weight or extend w_range to higher weights.")

    def model(w, f0, gamma1, gamma2, wc):
        return f_ansatz_5(w, float(w0), f0, a, gamma1, gamma2, float(wc))

    # Initial guess and bounds
    f0_guess  = f_vals[0] if len(f_vals) > 0 else 1e-5
    wc_guess  = float(ws[len(ws)//2]) if len(ws) > 0 else float(w0 * 3)
    p0        = [f0_guess, float(w0) * 0.8, float(w0) * 1.2, wc_guess]
    bounds    = ([1e-15, 0.1, 0.1, float(w0)],
                 [1.0,   50., 50., float(max(ws)) * 2 if len(ws) > 0 else 500.])

    try:
        popt, pcov = curve_fit(
            model, ws, f_vals,
            p0=p0, bounds=bounds, sigma=f_errs,
            maxfev=20000,
        )
        f0_fit, g1_fit, g2_fit, wc_fit = popt
        return {
            'w0': w0, 'a': a, 'f0': f0_fit,
            'gamma1': g1_fit, 'gamma2': g2_fit, 'wc': wc_fit,
            'pcov': pcov, 'fit_weights': ws, 'fit_f': f_vals,
        }
    except Exception as e:
        print(f"  curve_fit failed: {e}")
        return None

params = fit_ansatz(spectrum, K=K, w0=w0)

if params is not None:
    print(f"\n  Fit parameters:")
    print(f"    w0     = {params['w0']}          (fixed)")
    print(f"    a      = {params['a']:.4f}       (fixed = 1 - 1/2^K)")
    print(f"    f0     = {params['f0']:.4e}  (onset fraction)")
    print(f"    gamma1 = {params['gamma1']:.3f}         (low-w exponent)")
    print(f"    gamma2 = {params['gamma2']:.3f}         (high-w exponent)")
    print(f"    wc     = {params['wc']:.2f}        (crossover weight)")

    check(0 < params['f0'] < 0.5,
          f"f0 is small positive  [got {params['f0']:.4e}]")
    check(params['gamma1'] > 0,
          f"gamma1 > 0  [got {params['gamma1']:.3f}]")
    check(params['gamma2'] > 0,
          f"gamma2 > 0  [got {params['gamma2']:.3f}]")
    check(params['a'] == 0.5,
          f"a=0.5 for K=1  [got {params['a']}]")

    # Residuals: fitted curve vs measured spectrum
    print(f"\n  Residuals (fitted vs measured):")
    print(f"  {'w':>5}  {'measured':>12}  {'fitted':>12}  {'ratio':>8}")
    for w_r in sorted(spectrum):
        f_meas, _ = spectrum[w_r]
        if f_meas == 0:
            continue
        f_fit = f_ansatz_5(float(w_r), params['w0'], params['f0'], params['a'],
                           params['gamma1'], params['gamma2'], params['wc'])
        ratio = f_fit / f_meas if f_meas > 0 else float('inf')
        flag  = "  ← large residual" if abs(ratio - 1) > 0.5 else ""
        print(f"  {w_r:>5}  {f_meas:>12.4e}  {f_fit:>12.4e}  {ratio:>8.3f}{flag}")
else:
    failures.append("Ansatz fit failed")

# ---------------------------------------------------------------------------
# Step 8 — P(q) reconstruction vs Monte Carlo reference
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("STEP 8 — P(q) reconstruction vs Monte Carlo")
print("=" * 60)

from scipy.special import comb as scipy_comb

def p_from_ansatz(params, N, q_values):
    w0_ = params['w0']
    P   = np.zeros_like(q_values, dtype=float)
    # Cap summation: f(w) is negligibly different from a beyond w_max
    w_max = min(N, w0_ + 300)
    for w in range(w0_, w_max + 1):
        fw = f_ansatz_5(
            float(w), float(params['w0']), params['f0'], params['a'],
            params['gamma1'], params['gamma2'], params['wc'],
        )
        # Log-space to avoid underflow at small q
        with np.errstate(divide='ignore', invalid='ignore'):
            log_binom = (
                np.log(scipy_comb(N, w, exact=False))
                + w * np.log(np.where(q_values > 0, q_values, 1e-300))
                + (N - w) * np.log(np.where(q_values < 1, 1 - q_values, 1e-300))
            )
        P += fw * np.exp(np.clip(log_binom, -700, 0))
    return P

if params is not None:
    q_values = np.logspace(-4, -1, 200)
    P_ansatz = p_from_ansatz(params, N, q_values)

    # Find P at q=0.001 (the operating point used to generate the trace)
    p_op  = 0.001
    idx   = np.argmin(np.abs(q_values - p_op))
    P_at_p = float(P_ansatz[idx])

    print(f"\n  P(q) at selected error rates:")
    for q_show in [1e-4, 5e-4, 1e-3, 2e-3, 5e-3, 1e-2]:
        i = np.argmin(np.abs(q_values - q_show))
        print(f"    q={q_show:.0e}  →  P={P_ansatz[i]:.4e}")

    print(f"\n  Monte Carlo LER at p=0.001 : {mc_ler:.5f}  ({mc_predicted_fails}/{n_mc} shots)")
    print(f"  Ansatz P(q=0.001)          : {P_at_p:.5f}")

    if mc_ler > 0:
        ratio = P_at_p / mc_ler
        print(f"  Ratio (ansatz / MC)        : {ratio:.3f}  (expect 0.5–2.0 at this trial count)")
        check(0.1 < ratio < 10.0,
              f"P(q) order-of-magnitude agrees with Monte Carlo LER "
              f"[ansatz={P_at_p:.4e}, MC={mc_ler:.4e}, ratio={ratio:.2f}]",
              "Large ratio is expected with low trial counts — "
              "use ≥50,000 trials/weight for quantitative agreement")
    else:
        warn(False, "Monte Carlo LER is 0 — cannot compute ratio (too few shots)")

    # Sanity checks on the P(q) curve shape
    check(np.all(P_ansatz >= 0),
          "P(q) ≥ 0 everywhere")
    check(np.all(P_ansatz <= a + 1e-6),
          f"P(q) ≤ a={a} everywhere  [max={P_ansatz.max():.5f}]")
    check(np.all(np.diff(P_ansatz) >= -1e-10),
          "P(q) is monotonically non-decreasing in q")

    # P at very low q should be much smaller than at p=0.001
    P_very_low = float(P_ansatz[np.argmin(np.abs(q_values - 1e-4))])
    check(P_very_low < P_at_p * 0.1,
          f"P(1e-4) << P(1e-3) — curve shows correct scaling "
          f"[P(1e-4)={P_very_low:.4e}, P(1e-3)={P_at_p:.4e}]")

    # P at high q should approach the asymptote
    P_high = float(P_ansatz[-1])   # at q=0.1
    warn(P_high > 0.1,
         f"P(q=0.1) = {P_high:.3f} is approaching the high-q regime")
else:
    print("  Skipping P(q) reconstruction — fit failed in Step 7")

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

print("\n" + "=" * 60)
print("SUMMARY")
print("=" * 60)

if not failures:
    print(f"\033[92m\n  All checks passed.\033[0m")
else:
    print(f"\033[91m\n  {len(failures)} check(s) failed:\033[0m")
    for f in failures:
        print(f"    ✗ {f}")

print(f"""
  Key values for your implementation:
    N (faults)      = {N}
    M (detectors)   = {M}
    K (observables) = {K}
    a (asymptote)   = {a}
    w0 (onset)      = {w0_found}
    MC LER at p=0.001 = {mc_ler:.5f}  ({mc_predicted_fails}/{n_mc} shots)
""")

print("""
  Interpretation notes:
  - Step 7/8 accuracy depends heavily on trial count. The validation
    run uses a low trial count (--trials default 3000). For production
    use >= 50,000 trials/weight and ensure >= 100 observed failures at
    every weight point in your range.
  - A ratio of ansatz/MC outside 0.5-2.0 at this trial count is normal.
    Re-run with --trials 50000 once you have confirmed the wiring is correct.
  - If the Monte Carlo LER in the file is 0, regenerate the trace with
    more records (num_records=100000) or at a higher error rate.
""")
